---
- name: 📦 Crear PVC Longhorn para certificados
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Crear PVC certificados-longhorn
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ traefik_pvc_name }}"
            namespace: kube-system
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: "{{ traefik_pvc_size }}"
            storageClassName: "{{ traefik_pvc_sc }}"

    - name: 📨 Cargar wildcard-{crt,key} en el PVC (Job one-shot)
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: copy-wildcard-cert
            namespace: kube-system
          spec:
            ttlSecondsAfterFinished: 30
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: copier
                    image: alpine
                    command: ["/bin/sh","-c"]
                    args:
                      - |
                        cp /src/*.crt /dst/wildcard-socialdevs-tls.crt &&
                        cp /src/*.key /dst/wildcard-socialdevs-tls.key
                    volumeMounts:
                      - name: src
                        mountPath: /src
                      - name: dst
                        mountPath: /dst
                volumes:
                  - name: src
                    secret:
                      secretName: {{ internal_tls_secret_name }}
                  - name: dst
                    persistentVolumeClaim:
                      claimName: {{ traefik_pvc_name }}
